{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b0059a6f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Drone-Mapping-Assessment\n",
    "# This was the first validation of my skill set as a python programmer. I'd appreciate any feedback. \n",
    "\n",
    "\n",
    "from IPython.display import clear_output\n",
    "import os\n",
    "import platform\n",
    "\n",
    "#THE MAP\n",
    "N0 = ['#']    \n",
    "N1 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N2 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N3 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N4 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N5 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N6 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N7 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N8 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N9 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N10 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N11 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "N12 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "\n",
    "\n",
    "map_grids = [N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12]\n",
    "\n",
    "def visual_map(map_grids):\n",
    "\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(':12 : '+N12[1]+' : '+N12[2]+' : '+N12[3]+' : '+N12[4]+' : '+N12[5]+' : '+N12[6]+' : '+N12[7]+' : '+N12[8]+' : '+N12[9]+' : '+N12[10]+' : '+N12[11]+' : '+N12[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(':11 : '+N11[1]+' : '+N11[2]+' : '+N11[3]+' : '+N11[4]+' : '+N11[5]+' : '+N11[6]+' : '+N11[7]+' : '+N11[8]+' : '+N11[9]+' : '+N11[10]+' : '+N11[11]+' : '+N11[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(':10 : '+N10[1]+' : '+N10[2]+' : '+N10[3]+' : '+N10[4]+' : '+N10[5]+' : '+N10[6]+' : '+N10[7]+' : '+N10[8]+' : '+N10[9]+' : '+N10[10]+' : '+N10[11]+' : '+N10[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 9 : '+N9[1]+' : '+N9[2]+' : '+N9[3]+' : '+N9[4]+' : '+N9[5]+' : '+N9[6]+' : '+N9[7]+' : '+N9[8]+' : '+N9[9]+' : '+N9[10]+' : '+N9[11]+' : '+N9[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 8 : '+N8[1]+' : '+N8[2]+' : '+N8[3]+' : '+N8[4]+' : '+N8[5]+' : '+N8[6]+' : '+N8[7]+' : '+N8[8]+' : '+N8[9]+' : '+N8[10]+' : '+N8[11]+' : '+N8[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 7 : '+N7[1]+' : '+N7[2]+' : '+N7[3]+' : '+N7[4]+' : '+N7[5]+' : '+N7[6]+' : '+N7[7]+' : '+N7[8]+' : '+N7[9]+' : '+N7[10]+' : '+N7[11]+' : '+N7[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 6 : '+N6[1]+' : '+N6[2]+' : '+N6[3]+' : '+N6[4]+' : '+N6[5]+' : '+N6[6]+' : '+N6[7]+' : '+N6[8]+' : '+N6[9]+' : '+N6[10]+' : '+N6[11]+' : '+N6[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 5 : '+N5[1]+' : '+N5[2]+' : '+N5[3]+' : '+N5[4]+' : '+N5[5]+' : '+N5[6]+' : '+N5[7]+' : '+N5[8]+' : '+N5[9]+' : '+N5[10]+' : '+N5[11]+' : '+N5[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 4 : '+N4[1]+' : '+N4[2]+' : '+N4[3]+' : '+N4[4]+' : '+N4[5]+' : '+N4[6]+' : '+N4[7]+' : '+N4[8]+' : '+N4[9]+' : '+N4[10]+' : '+N4[11]+' : '+N4[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 3 : '+N3[1]+' : '+N3[2]+' : '+N3[3]+' : '+N3[4]+' : '+N3[5]+' : '+N3[6]+' : '+N3[7]+' : '+N3[8]+' : '+N3[9]+' : '+N3[10]+' : '+N3[11]+' : '+N3[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 2 : '+N2[1]+' : '+N2[2]+' : '+N2[3]+' : '+N2[4]+' : '+N2[5]+' : '+N2[6]+' : '+N2[7]+' : '+N2[8]+' : '+N2[9]+' : '+N2[10]+' : '+N2[11]+' : '+N2[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(': 1 : '+N1[1]+' : '+N1[2]+' : '+N1[3]+' : '+N1[4]+' : '+N1[5]+' : '+N1[6]+' : '+N1[7]+' : '+N1[8]+' : '+N1[9]+' : '+N1[10]+' : '+N1[11]+' : '+N1[12]+' :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "    print(':   : 1 : 2 : 3 : 4 : 5 : 6 : 7 : 8 : 9 :10 :11 :12 :')\n",
    "    print(':---:---:---:---:---:---:---:---:---:---:---:---:---:')\n",
    "\n",
    "    \n",
    "    #Start Point / CALLING THE FILE\n",
    "\n",
    "def file_name():\n",
    "    \n",
    "    \n",
    "    finish = False\n",
    "    file = ''\n",
    "    \n",
    "    while finish == False:\n",
    "        \n",
    "        file = (input('Please input file name or STOP:'))\n",
    "        \n",
    "        if file.lower() == 'stop':\n",
    "            \n",
    "            finish = True\n",
    "        \n",
    "        else:\n",
    "            \n",
    "            try:\n",
    "                if platform.system() == 'Windows': \n",
    "                    OS = r\"\\\"\"\n",
    "                \n",
    "                else:\n",
    "                    OS = '/'\n",
    "\n",
    "                file_location = os.getcwd()\n",
    "                cwd = os.getcwd()\n",
    "                file_location = cwd+OS+file                        \n",
    "    \n",
    "                f = open(file_location, \"r\", encoding = \"UTF-8\")\n",
    "                \n",
    "                \n",
    "                read_coordinates = f.readlines()\n",
    "                \n",
    "                coordinates = []  \n",
    "\n",
    "                for num in read_coordinates:\n",
    "                    coords = num.replace('\\n','')\n",
    "                    coordinates.append(coords)\n",
    "\n",
    "                x = int(coordinates[0])\n",
    "                y = int(coordinates[1])\n",
    "                directions = coordinates[2:]\n",
    "\n",
    "\n",
    "                return x,y, directions, file\n",
    "            \n",
    "            except:\n",
    "                clear_output()\n",
    "                print('File Not Found')\n",
    "             \n",
    "    else:\n",
    "        return finish    \n",
    "      \n",
    "      \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "def start_place_marker(board, N, E, marker):\n",
    "    board[N][E] = marker\n",
    "\n",
    "\n",
    "def direction_func(directions):\n",
    "    \n",
    "    \n",
    "    valid = True\n",
    "    finish = False\n",
    "    \n",
    "    navigation = ['N','E','S','W']\n",
    "    route = []\n",
    "    \n",
    "    position_N = sp_N\n",
    "    position_E = sp_E\n",
    "    \n",
    "    \n",
    "    while finish == False and valid == True:\n",
    "    \n",
    "        \n",
    "        for num in directions[0]:\n",
    "                \n",
    "                if num == 'N':\n",
    "                    position_N = position_N+1\n",
    "\n",
    "                if num == 'E':\n",
    "                    position_E = position_E+1\n",
    "\n",
    "                if num == 'S':\n",
    "                    position_N = position_N-1\n",
    "\n",
    "                if num == 'W':\n",
    "                    position_E = position_E-1 \n",
    "                    \n",
    "                \n",
    "                \n",
    "                if position_N not in range(1,13) or position_E not in range(1,13):\n",
    "                    valid = False\n",
    "                \n",
    "                \n",
    "                else:\n",
    "                    if num not in navigation:\n",
    "                        valid = False\n",
    "                    \n",
    "                    else:   \n",
    "                        if len(num)>1:\n",
    "                            valid = False\n",
    "                        \n",
    "                        else:\n",
    "                        \n",
    "                            coordinates = position_E, position_N\n",
    "\n",
    "                            directions.pop(0)\n",
    "\n",
    "                            route.extend([coordinates])\n",
    "                            \n",
    "                            if len(directions)== 0:\n",
    "\n",
    "                                finish = True\n",
    "    \n",
    "\n",
    "    else:\n",
    "        if valid == False:\n",
    "            return valid\n",
    "        \n",
    "        else:\n",
    "            return route\n",
    "            \n",
    "\n",
    "\n",
    "def place_marker(map_grids, y, x, marker):\n",
    "    map_grids[y][x] = marker\n",
    "\n",
    "\n",
    "completed = False\n",
    "while completed == False:\n",
    "    \n",
    "    #VARIABLES / Within While Loop to reset\n",
    "    N0 = ['#']    \n",
    "    N1 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N2 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N3 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N4 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N5 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N6 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N7 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N8 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N9 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N10 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N11 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    N12 = ['#',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']\n",
    "    map_grids = [N0,N1,N2,N3,N4,N5,N6,N7,N8,N9,N10,N11,N12]\n",
    "    \n",
    "    #WHILE LOOP VARIABLES\n",
    "    game_on = True\n",
    "    output = False\n",
    "    route = []\n",
    "    \n",
    "    \n",
    "    f_name = file_name()\n",
    "    \n",
    "    #IF F_NAME = TRUE, STOP HAS BEEN CALLED / BREAKS PRIMARY WHILE LOOP\n",
    "    if f_name == True:\n",
    "        completed = True\n",
    "        \n",
    "        \n",
    "        \n",
    "    #PLOTTING COORDINATES    \n",
    "    else:\n",
    "        \n",
    "        x = f_name[0]\n",
    "        y = f_name[1]\n",
    "        directions = f_name[2]\n",
    "        \n",
    "        starting_position = x, y\n",
    "        \n",
    "        sp_E = starting_position[0]  \n",
    "        sp_N = starting_position[1]\n",
    "        \n",
    "        move_position = direction_func(directions)  \n",
    "        \n",
    "\n",
    "        if move_position == False:\n",
    "            clear_output()\n",
    "            print('Error: The route is outside of the grid.')\n",
    "            \n",
    "            \n",
    "        \n",
    "        else:\n",
    "\n",
    "            start_place_marker(map_grids, sp_N, sp_E, 'x')\n",
    "\n",
    "            \n",
    "            while game_on == True:\n",
    "                \n",
    "                move_positionE = move_position[0][0]\n",
    "                move_positionN = move_position[0][1]\n",
    "                \n",
    "                place_marker(map_grids, move_positionN, move_positionE, 'x')\n",
    "                \n",
    "                route.extend((move_positionE, move_positionN))\n",
    "                move_position.pop(0)\n",
    "                \n",
    "                if len(move_position) == 0:\n",
    "                    game_on = False\n",
    "                    \n",
    "                    clear_output()\n",
    "                    print(f_name[3])\n",
    "                    visual_map(map_grids)\n",
    "                    print('Coordinates')\n",
    "                    print(x,y)\n",
    "\n",
    "            while output == False:\n",
    "                print(route[0],route[1])\n",
    "                route.pop(0)\n",
    "                route.pop(0)\n",
    "                if len(route)==0:\n",
    "                    output = True\n",
    "                    \n",
    "\n",
    "else:\n",
    "    completed"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
